image: node:12.18-alpine

services:
  - docker:dind

variables:
  WORK_DIR: .
  NODE_ENV: development
  DOCKER_DRIVER: overlay2
  DOCKER_FILE: docker/Dockerfile
  DOCKER_IMAGE_FILE: Dockerfile
  DOCKER_BUILD_CONTEXT: .
  DOCKER_COMPOSE_FILE: docker/docker-stack.yml
  DOCKER_IMAGE: ${CI_PROJECT_PATH_SLUG}:${CI_PIPELINE_ID}-${CI_COMMIT_SHORT_SHA}
  DOCKER_BUILD_IMAGE: mbal/api:${CI_COMMIT_TAG}-${CI_COMMIT_SHORT_SHA}
  DOCKER_REGISTRY_LOCAL_URL: localhost:5000
  DOCKER_STACK_NAME: ${CI_PROJECT_PATH_SLUG}

cache:
  paths:
    - node_modules/

stages:
  - preparation
  - eslint
  - bundle
  - deploy

preparation:
  stage: preparation
  only:
    - deploy
    - merge_requests
  tags:
    - klc-api
  script:
    - yarn install --ignore-optional
  variables:
    CI: 'true'

eslint:
  stage: eslint
  only:
    - merge_requests
  tags:
    - klc-api
  before_script:
    - cd ${WORK_DIR}
  script:
    - yarn lint
  variables:
    CI: 'true'

bundle:
  stage: bundle
  only:
    - deploy
  tags:
    - klc-api
  before_script:
    - cd ${WORK_DIR}
  script:
    - yarn build ${YARN_BUILD_ARGS}
  artifacts:
    name: ${CI_PROJECT_NAME}-${CI_COMMIT_SHORT_SHA}
    expire_in: 1h
    paths:
      - ${WORK_DIR}/dist
  variables:
    CI: 'false'

deploy:
  stage: deploy
  image: docker:dind
  only:
    - deploy
  tags:
    - klc-api
  before_script:
    # move to work dir
    - cd ${WORK_DIR}
    # validate config
    - |
      if [ ! -f ${DOCKER_FILE} ] || [ ! -f ${DOCKER_COMPOSE_FILE} ]; then
        echo "ERROR! ${DOCKER_FILE} or ${DOCKER_COMPOSE_FILE} does not exist."
        exit 1
      fi
    - |
      if [ ! -z ${DOCKER_REGISTRY_URL} ]; then
        echo "DOCKER_REGISTRY_URL: ${DOCKER_REGISTRY_URL}"
        if [ -z ${DOCKER_REGISTRY_USERNAME} ] || [ -z ${DOCKER_REGISTRY_PASSWORD} ]; then
          echo "ERROR! DOCKER_REGISTRY_USERNAME and DOCKER_REGISTRY_PASSWORD must be setted when DOCKER_REGISTRY_URL is setted."
          exit 1
        fi
      fi

    # login docker registry
    - |
      if [ ! -z "${DOCKER_REGISTRY_URL}" ]
      then
        echo ${DOCKER_REGISTRY_PASSWORD} | docker login \
          --username ${DOCKER_REGISTRY_USERNAME} \
          --password-stdin \
          ${DOCKER_REGISTRY_URL}
        export DOCKER_IMAGE=${DOCKER_REGISTRY_URL}/$DOCKER_IMAGE
      fi

  script:
    # build docker
    - docker build -f ${DOCKER_FILE} -t ${DOCKER_IMAGE} ${DOCKER_BUILD_CONTEXT}
    # push docker
    - if [ ! -z "${DOCKER_REGISTRY_URL}" ]; then docker push ${DOCKER_IMAGE}; fi
    # deploy
    - |
      if [ -z "${DOCKER_HOST_DEPLOY}" ]
      then
        docker stack deploy --compose-file ${DOCKER_COMPOSE_FILE} ${DOCKER_STACK_NAME}
      else
        docker -H ${DOCKER_HOST_DEPLOY} stack deploy --compose-file ${DOCKER_COMPOSE_FILE} ${DOCKER_STACK_NAME} --with-registry-auth
      fi
