version: '3.3'
services:
  klc_api:
    image: ${DOCKER_IMAGE}
    restart: unless-stopped
    environment:
      TZ: UTC
      PORT: 3000
      NODE_ENV: ${NODE_ENV}
      DASHBOARD_DOMAIN: https://admin-klc.ntq.solutions
      WEB_DOMAIN: https://klc.ntq.solutions
      DATABASE_PASSWORD: ${DATABASE_PASSWORD}
      DATABASE_NAME: ${DATABASE_NAME}
      DATABASE_USER: ${DATABASE_USER}
      DATABASE_HOST: postgres
      DATABASE_SYNC: ${DATABASE_SYNC}
      DATABASE_PORT: 5432
      JWT_SECRET: my_secret
      AWS_ACCESS_KEY_ID: ${AWS_ACCESS_KEY_ID}
      AWS_SECRET_KEY_ACCESS: ${AWS_SECRET_KEY_ACCESS}
      AWS_SES_REGION: ${AWS_SES_REGION}
      AWS_SNS_REGION: ${AWS_SNS_REGION}
      AWS_SES_SENDER_EMAIL: ${AWS_SES_SENDER_EMAIL}
      AWS_S3_BUCKET_NAME: ${AWS_S3_BUCKET_NAME}
    depends_on:
      - postgres
    volumes:
      - /home/ntq/klc/uploads:/home/node/uploads
    networks:
      - klc_network
      - base_base_network

networks:
  klc_network:
    driver: overlay
    attachable: true
  base_base_network:
    external: true
